name: Code Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:

    runs-on: macOS-latest

    steps:
    # - uses: actions/checkout@main
    # - name: CodeCover
    #   run: sh ./Scripts/ci-ios-code-coverage.sh

    - uses: actions/checkout@v2
    - name: Test
      run: |
        xcodebuild -scheme doryQuizTests -resultBundlePath TestResults test

    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
        if: success() || failure()
        # ^ This is important because the action will be run
        # even if the test fails in the previous step.