name: Code Coverage

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@main
    - name: CodeCover
      run: sh ./Scripts/ci-ios-code-coverage.sh

    - name: Report coverage
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ./coverage/lcov.info