name: CodeCov

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Build App
    #   working-directory: doryQuiz
    #   run: xcodebuild -project "doryQuiz.xcodeproj" -scheme "doryQuiz" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO  
    # - name: Run tests
    #   working-directory: doryQuiz
    #   run: xcodebuild clean test -project "doryQuiz.xcodeproj" -scheme "doryQuiz" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
    - name: Archive code coverage results
    uses: actions/upload-artifact@v3
    with:
      - name: CodeCover
      run: sh ./Scripts/ci-ios-code-coverage.sh


