
name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ["platform=iOS Simulator,OS=16.2, name=iPhone 14 Pro Max"]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Force Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Build
        working-directory: doryQuiz
        run: |
          xcodebuild clean build -project doryQuiz.xcodeproj -scheme doryQuiz -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Test
        run: |
          xcodebuild clean test -project oryQuiz.xcodeproj -scheme doryQuizs -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO