name: Code Coverage

on:
  pull_request:
    paths:
      - "doryQuiz/doryQuizTests/doryQuizTests.swift"

jobs:
  build:
    runs-on: macos-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GH_TOKEN: ${{ github.token }}

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@main
    
    - name: Code Cover
      run: sh ./Scripts/ci-ios-code-coverage.sh
      env:
        GH_TOKEN: ${{ github.token }}

