name: Code Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:

    runs-on: macOS-latest

    steps:
    # - uses: actions/checkout@main
    # - name: CodeCover
    #   run: sh ./Scripts/ci-ios-code-coverage.sh
    # - name: Create issue
    #   run: |
    #     curl --request POST \
    #     --url https://api.github.com/QA-NUPED/swift-doryquiz/issues \
    #     --header 'authorization: Bearer ${{ secrets.github_token }}' \
    #     --header 'content-type: application/json' \
    #     --data '{
    #       "title": "Automated issue for commit: ${{ github.sha }}",
    #       "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
    #       }' \
    #     --fail
    - name: Run tests
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: doryQuiz/doryQuiz.xcodeproj
        scheme: IndexedDataStore
        derived-data-path: DerivedData/doryQuiz-edocehqkdfpyosalmqwahiqdwpii/Build/ProfileData/192655B2-4F13-4E3D-8B9F-F1B94548CE05/Coverage.profdata
        destination: "platform=iOS Simulator,OS=latest,name=iPhone 14"
        action: test
        enable-code-coverage: true

    - name: Test Coverage
      uses: maxep/xcodebuild-lcov-action@0.1.0
      with:
        derived-data-path: DerivedData/doryQuiz-edocehqkdfpyosalmqwahiqdwpii/Build/ProfileData/192655B2-4F13-4E3D-8B9F-F1B94548CE05/Coverage.profdata
        target: CodeCoverage.xcresult
        output-file: ./coverage/lcov.info