
name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ["platform=iOS Simulator,OS=16.2, name=iPhone 14 Pro Max"]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Test
        working-directory: doryQuiz
        run: |
          xcodebuild clean test -project doryQuiz.xcodeproj -scheme doryQuizs -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
    - name: Build App
      - name: Build
        working-directory: doryQuiz
        run: |
          xcodebuild clean build -project doryQuiz.xcodeproj -scheme doryQuiz -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
