name: Code Coverage

on:
  pull_request:
    paths:
      - "doryQuiz/doryQuizTests/doryQuizTests.swift"

jobs:
  build1:
    runs-on: macos-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@main
    - name: Code Cover
      run: sh ./Scripts/ci-ios-code-coverage1.sh
      env:
        GH_TOKEN: ${{ github.token }}
