name: Code Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: CodeCover
      run: sh ./Scripts/ci-ios-code-coverage.sh

    # - name: Run tests
    #   uses: sersoft-gmbh/xcodebuild-action@v1
    #   with:
    #     project: doryQuiz/doryQuiz.xcodeproj
    #     scheme: doryQuizTests
    #     derived-data-path: ./output
    #     destination: "OS=14.4,name=iPhone 12 Pro"
    #     action: test
    #     enable-code-coverage: true

    - name: Test Coverage
      uses: maxep/xcodebuild-lcov-action@0.1.0
      with:
        derived-data-path: ./CodeCoverage.xcresult/Info.plist
        target: doryQuiz.app
        output-file: ./coverage/lcov.info