name: Code Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: macos-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GH_TOKEN: ${{ github.token }}

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@main
    - name: CodeCover
      run: |
          output=$(sh ./Scripts/ci-ios-code-coverage.sh)
          PR_COMMENT="$output"
          gh pr comment $PR_NUMBER --body "$PR_COMMENT"